"""SQLAlchemy ORM models for Benchmarker.

Models: BenchmarkSetRow, BenchmarkQuestionRow, TestRunRow, TestResultRow.
All tables are scoped to a workspace via workspace_id on benchmark_sets (no FK — workspaces live in Memgraph).
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import (
    JSON,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import relationship

from metatron.storage.pg_models import Base


class BenchmarkSetRow(Base):  # type: ignore[misc]
    """Benchmark set (generation session) scoped to a workspace."""

    __tablename__ = "benchmark_sets"

    id = Column(String(64), primary_key=True)
    workspace_id = Column(String(64), nullable=False)
    name = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    connection_id = Column(String(64), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    tokens_used = Column(Integer, default=0)
    question_count = Column(Integer, default=0)

    questions = relationship(
        "BenchmarkQuestionRow",
        back_populates="benchmark_set",
        cascade="all, delete-orphan",
    )
    test_runs = relationship(
        "TestRunRow",
        back_populates="benchmark_set",
        cascade="all, delete-orphan",
    )

    __table_args__ = (Index("ix_benchmark_sets_workspace", "workspace_id"),)


class BenchmarkQuestionRow(Base):  # type: ignore[misc]
    """Question generated by BenchmarkQED, belonging to a benchmark set."""

    __tablename__ = "benchmark_questions"

    id = Column(String(64), primary_key=True)
    benchmark_set_id = Column(
        String(64),
        ForeignKey("benchmark_sets.id", ondelete="CASCADE"),
        nullable=False,
    )
    text = Column(Text, nullable=False)
    question_type = Column(String(20), nullable=False)  # data_local / data_global
    references = Column(JSON, nullable=True)
    attributes = Column(JSON, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    benchmark_set = relationship("BenchmarkSetRow", back_populates="questions")

    __table_args__ = (Index("ix_benchmark_questions_set", "benchmark_set_id"),)


class TestRunRow(Base):  # type: ignore[misc]
    """Test run with aggregated average metrics."""

    __tablename__ = "test_runs"

    id = Column(String(64), primary_key=True)
    benchmark_set_id = Column(
        String(64),
        ForeignKey("benchmark_sets.id", ondelete="CASCADE"),
        nullable=False,
    )
    name = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    total_tests = Column(Integer, default=0)
    avg_correctness = Column(Float, nullable=True)
    avg_answer_relevancy = Column(Float, nullable=True)
    avg_faithfulness = Column(Float, nullable=True)
    avg_context_precision = Column(Float, nullable=True)
    avg_context_recall = Column(Float, nullable=True)
    avg_confidence = Column(Float, nullable=True)
    avg_ndcg_at_10 = Column(Float, nullable=True)
    avg_mrr = Column(Float, nullable=True)
    avg_precision_at_k = Column(Float, nullable=True)

    benchmark_set = relationship("BenchmarkSetRow", back_populates="test_runs")
    test_results = relationship(
        "TestResultRow",
        back_populates="test_run",
        cascade="all, delete-orphan",
    )

    __table_args__ = (Index("ix_test_runs_benchmark_set", "benchmark_set_id"),)


class TestResultRow(Base):  # type: ignore[misc]
    """Single test result with per-question metrics and white-box context."""

    __tablename__ = "test_results"

    id = Column(String(64), primary_key=True)
    test_run_id = Column(
        String(64),
        ForeignKey("test_runs.id", ondelete="CASCADE"),
        nullable=False,
    )
    question = Column(JSON, nullable=True)
    actual_answer = Column(Text, nullable=False)
    correctness = Column(Float, nullable=True)
    answer_relevancy = Column(Float, nullable=True)
    faithfulness = Column(Float, nullable=True)
    context_precision = Column(Float, nullable=True)
    context_recall = Column(Float, nullable=True)
    confidence = Column(Float, nullable=True)
    ndcg_at_10 = Column(Float, nullable=True)
    mrr = Column(Float, nullable=True)
    precision_at_k = Column(Float, nullable=True)
    claim_scores = Column(JSON, nullable=True)
    context = Column(JSON, nullable=True)  # white-box data

    test_run = relationship("TestRunRow", back_populates="test_results")

    __table_args__ = (Index("ix_test_results_run", "test_run_id"),)
