name: Deploy Metronix to Kubernetes

on:     
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v5
        with:
          version: 'develop'   

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
        # echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: Validate Kubernetes manifest
        run: kubectl apply -f install/metronix-k8s.yaml --dry-run=client

      - name: Deploy to Kubernetes
        run: kubectl apply -f install/metronix-k8s.yaml
